Add master branch in SonarQube

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -51,9 +51,19 @@ phases:
     commands: 
       - echo Starting build in $(pwd) 
       - echo Build started on $(date) 
+      - pip install -q coverage
       - echo ${S3Bucket} 
       - echo ${KMSKey} 
       - echo HOME ${HOME} 
+      # install sonar-scanner
+      - mkdir /opt/sonarscanner
+      - cd /opt/sonarscanner
+      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -q
+      - unzip -q sonar-scanner-cli-4.6.2.2472-linux.zip
+      - rm sonar-scanner-cli-4.6.2.2472-linux.zip
+      - ln -s /opt/sonarscanner/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
+      - pip install -q pypika
+      - cd $curr_dir
       # build project folder and package build file 
       - ls -lrt "$curr_dir"
       - x=$(ls "$(pwd)")
@@ -65,10 +75,52 @@ phases:
               echo "Processing - $mydir"; 
               echo "Current dir - $(pwd)"; 
               if [ -f requirements.txt ]; then
+                python -m venv "${mydir}-venv";
+                . ${mydir}-venv/bin/activate ;
                 if [ -f dependencies.txt ]; then
                   pip install -q -r dependencies.txt -t ./lib ;
                 fi;
-                zip -r "$mydir.zip" .;               
+                pipInstallCheckExitCode=$(echo $?);
+                if [ $pipInstallCheckExitCode -ne 0 ]; then
+                  echo "\n#===================================================================#\n";
+                  echo "[ERROR] ---> pip install of dependencies failed for the project '$mydir'. Exit code => '$pipInstallCheckExitCode'! Aborting Build!";
+                  echo "\n#===================================================================#\n";
+                  deactivate;
+                  exit 1;
+                fi;
+                zip -q -r "$mydir.zip" . -x "./${mydir}-venv/*";
+                coverage run -m unittest discover -s tests;
+                testCaseExecutionExitCode=$?;
+                deactivate;
+                if [ $testCaseExecutionExitCode -ne 0 ]; then
+                  echo "\n#===================================================================#\n";
+                  echo "[ERROR] ---> Some of the TDD/Code Coverage test cases failed for the project '$mydir'. Exit code => '$testCaseExecutionExitCode'! Aborting Build!";
+                  echo "\n#===================================================================#\n";
+                fi;
+                coverage report --omit tests/*;
+                coverage xml;
+                sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.python.coverage.reportPaths="coverage.xml" -Dsonar.branch.name="master";
+                echo "Printing dir contents to find the coverage.xml file . . . ";
+                ls -l;
+                if [ -f "../SonarqubeQualityChecker.sh" ] && [ -f "sonar-project.properties" ]; then
+                  cd ..;
+                  tr -d '\r' < SonarqubeQualityChecker.sh > CleanSonarqubeQualityChecker.sh;
+                  bash CleanSonarqubeQualityChecker.sh $mydir "/da-sca-sonar/sonar/sonar-common-token" "master";
+                  qualityCheckExitCode=$(echo $?);
+                  if [ $qualityCheckExitCode -ne 0 ]; then
+                    echo "\n#===================================================================#\n";
+                    echo "[ERROR] ---> The Sonarqube Quality Gate condition verification failed for the project '$mydir'! Aborting Build!";
+                    echo "\n#===================================================================#\n";
+                    exit 1;
+                  fi;
+                  cd "$mydir";
+                else
+                  echo "\n#--------------------------------------------------------------------------------#\n";
+                  echo "The Sonarqube Quality Gate condition verification script ('SonarQubeQualityChecker.sh') is missing from this repo AND/OR ('sonar-project.properties') is missing from this project => $mydir\n";
+                  echo "Please, add the 'SonarQubeQualityChecker.sh' file in the root repo (same folder as this build spec file) AND/OR the appropriate 'sonar-project.properties' in the project => $mydir\n";
+                  echo "Build will proceed, but note that there was no Sonaqube Quality Gate verification done for the project => $mydir\n";
+                  echo "\n#--------------------------------------------------------------------------------#\n";
+                fi;              
                 cp "$mydir.zip" "$curr_dir/target"; 
               else           
                 echo "unknown platform"; 
