EDGE-3277: Fail the codebuild base on SonarQube Condition for Python Repos & update spartans pipelines for sonarQube

diff --git a/buildspec-dev.yaml b/buildspec-dev.yaml
--- a/buildspec-dev.yaml
+++ b/buildspec-dev.yaml
@@ -52,24 +52,53 @@ phases:
       # build project folder and package build file 
       - ls -lrt "$curr_dir"
       - x=$(ls "$(pwd)")
+      - echo -e "\n#====================================================================================================================================================================================#\n\nEDGE Build Actions Start . . .\n\n#====================================================================================================================================================================================#\n"
       - for d in $x ;
         do
           mydir=${d};   
-          if [ $mydir != "EDGE-J1939-BDD" ] && [ $mydir != "cloudformation" ] && [ $mydir != ".settings" ] && [ $mydir != "libraries" ] && [ $mydir != "target" ] && [ $mydir != "edge.iot.topic_rules" ] && [ -d "$mydir" ]; then 
+          if [ $mydir != "EDGE-J1939-BDD" ] && [ $mydir != "cloudformation" ] && [ -d "$mydir" ]; then
               cd "$mydir"; 
               echo "Processing - $mydir"; 
               echo "Current dir - $(pwd)";  
               if [ -f requirements.txt ]; then
                 pip install -r requirements.txt -t ./lib ;
                 zip -r "$mydir.zip" .;
-                pytest --cov-report xml:coverage.xml --cov=tests/ ;
-                sonar-scanner -X -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.python.coverage.reportPath="/coverage.xml";                                     
-                cp "$mydir.zip" "$curr_dir/target";        
+                coverage run -m unittest discover -s tests;
+                testCaseExecutionExitCode=$?;
+                if [ $testCaseExecutionExitCode -ne 0 ]; then
+                  echo -e "\n#====================================================================================================================================================================================#\n";
+                  echo "[ERROR] ---> Some of the TDD/Code Coverage test cases failed for the project '$mydir'. Exit code => '$testCaseExecutionExitCode'! Aborting Build!";
+                  echo -e "\n#====================================================================================================================================================================================#\n";
+                  exit 1;
+                fi;
+                coverage report --omit tests/* && coverage xml;
+                sonar-scanner -X -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.python.coverage.reportPaths="coverage.xml";
+                if [ -f "../SonarqubeQualityChecker.sh" ] && [ -f "sonar-project.properties" ]; then
+                  cd ..;
+                  tr -d '\r' < SonarqubeQualityChecker.sh > CleanSonarqubeQualityChecker.sh;
+                  bash CleanSonarqubeQualityChecker.sh $mydir "/da-sca-sonar/sonar/sonar-common-token";
+                  qualityCheckExitCode=$(echo $?);
+                  if [ $qualityCheckExitCode -ne 0 ]; then
+                    echo -e "\n#====================================================================================================================================================================================#\n";
+                    echo "[ERROR] ---> The Sonarqube Quality Gate condition verification failed for the project '$mydir'! Aborting Build!";
+                    echo -e "\n#====================================================================================================================================================================================#\n";
+                    exit 1;
+                  fi;
+                  cd "$mydir";
+                else
+                  echo -e "\n#====================================================================================================================================================================================#\n";
+                  echo "The Sonarqube Quality Gate condition verification script ('SonarQubeQualityChecker.sh') is missing from this repo AND/OR ('sonar-project.properties') is missing from this project";
+                  echo -e "The Sonarqube Quality Gate condition verification script ('SonarQubeQualityChecker.sh') is missing from this repo AND/OR ('sonar-project.properties') is missing from this project => $mydir\n";
+                  echo -e "\n#====================================================================================================================================================================================#\n";
+                fi;
+                cp "$mydir.zip" "$curr_dir/target";
               else           
-                echo "unknown platform"; 
+                echo -e "\n#====================================================================================================================================================================================#\n";
+                echo "The programming platform for the project => $mydir could not be identified! Aborting build!";
+                echo -e "\n#====================================================================================================================================================================================#\n";
                 break;        
               fi;        
-              cd ..;     
+              cd ..;
           fi;  
         done || exit 1 
       - ls -lrt "$curr_dir/target" 
